2025-01-24 15:03:49,798:ERROR:{'message': 'division by zero', 'detail': 'Traceback (most recent call last):\n  File "C:\\Users\\Home\\python_exception\\custom_logging.py", line 11, in <module>\n    10 / 0\n    ~~~^~~\nZeroDivisionError: division by zero\n'}
